package com.InKyung.review;

import com.querydsl.jpa.impl.JPAQueryFactory;
import jakarta.persistence.EntityManager;
import lombok.RequiredArgsConstructor;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@RequiredArgsConstructor //private 변수는 @AllArgsConstructor 말고 @RequiredArgsConstructor도 가능.
@Configuration
public class QuerydsConfig {
    private final EntityManager em;

    @Bean // @Bean은 메소드 수준의 어노테이션. Spring Bean을 등록하기 위한 어노테이션입니다.
    // Spring Bean이란 스프링이 관리하는 오브젝트로, 스프링 프레임워크 컨테이너에 의해 인스턴스화되고, 구성되고, 관리되는 객체.
    public JPAQueryFactory queryFactory(){
        return new JPAQueryFactory(em);
    }
}
/*
Hibernate: drop table if exists test cascade
Hibernate: create table test (age integer, id bigint generated by default as identity, name varchar(255), primary key (id))
: H2 DB에 테이블 생성 의미.
 */
