package com.InKyung.review;

import com.querydsl.jpa.impl.JPAQueryFactory;
import jakarta.persistence.EntityManager;
import lombok.RequiredArgsConstructor;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@RequiredArgsConstructor //private 변수는 @AllArgsConstructor 말고 @RequiredArgsConstructor도 가능.
@Configuration
public class QuerydsConfig {
    private final EntityManager em;

    @Bean
    public JPAQueryFactory queryFactory(){
        return new JPAQueryFactory(em);
    }
}
/*
Hibernate: drop table if exists test cascade
Hibernate: create table test (age integer, id bigint generated by default as identity, name varchar(255), primary key (id))
: H2 DB에 테이블 생성 의미.
 */
